### ISSUE TITLE
Tag v2 not pointing to latest v2.3.0

### ISSUE THREAD

**Issue by nolddor** [sergeysova/jq-action#10]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

sergeysova/jq-action@v2

### Steps to reproduce

Create your .github workflow descriptor file and use this action:

```
uses: sergeysova/jq-action@v2
with:
  cmd: jq -n env
```

### Expected behavior

After #9 being merged. The following error most NOT appear anymore at github action output logs:

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

### Actual behavior

It stills appear as tag v2 point to commit acfe8e3 instead of commit a3f0d4f

**Comment by nolddor** [comment]
Any chance you can quickfix this @sergeysova  ?
Thanks!

**Comment by sergeysova** [comment]
@nolddor Fixed!
<img width="505" alt="image" src="https://user-images.githubusercontent.com/5620073/218971381-c2ebee48-18c8-4d36-a26a-bf344d39faea.png">

**Comment by nolddor** [comment]
Thx!
